version: '3'
services:
  app-flask:
    container_name: 'app-flask'
    build:
      context: .
      dockerfile: app-flask/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    restart: always

  app-react:
    container_name: 'app-react'
    build:
      context: .
      dockerfile: app-react/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app-flask
    restart: always

  app-email:
    container_name: 'app-email'
    build:
      context: .
      dockerfile: app-email/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    restart: always

  rabbitmq:
    image: "rabbitmq:3.8"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
    restart: always

  mongodb:
    image: "mongo:latest"
    container_name: 'mongodb'
    ports:
      - "27017:27017"
