version: '3'
services:
  app-flask:
    container_name: 'app-flask'
    build:
      context: .
      dockerfile: app-flask/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    restart: always

  app-react:
    container_name: 'app-react'
    build:
      context: .
      dockerfile: app-react/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app-flask
    restart: always

  app-email:
    container_name: 'app-email'
    build:
      context: .
      dockerfile: app-email/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    restart: always

  rabbitmq:
    image: "rabbitmq:3.8"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: 'minio'
    volumes:
      - ./data-1:/data-1
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data-1

  mongodb:
    image: "mongo:latest"
    container_name: 'mongodb'
    ports:
      - "27017:27017"
